### ISSUE TITLE
Credit where credit's due

### ISSUE THREAD

**Issue by kirkbushell** [BenConstable/phpspec-laravel#25]
This is not an issue, but I like to give praise/credit where its due. Want to thank you and give kudos for a great little package. Well written, easy to use. Documentation needs a little more information (took me a while to figure out why the lib was trying to load App\Http\Kernel), but other than that - great work!

**Comment by BenConstable** [comment]
Thanks very much! Glad you've found the package useful and that it's helping you as well as me.

With Laravel 5 is getting its first release this week, I'll be tidying up the `laravel-5` branch (including all of the docs) and releasing version 2.0 in the near future.

Thanks again!
