### ISSUE TITLE
Throwing an error on L5

### ISSUE THREAD

**Issue by prodeveloper** [BenConstable/phpspec-laravel#34]
I have just installed the plugin but when I try to run phpspec an error is thrown.
```bash
[ErrorException]                                                                                                              
Declaration of App\Providers\BusServiceProvider::boot() should be compatible with Illuminate\Support\ServiceProvider::boot() 
```
Version of phpspec laravel is *~2.0@dev* and for laravel *~5.0*

The class just doesn't initialize. But works fine if I switch the out *LaravelObjectBehavior* for *ObjectBehavior*

Please assist.

**Comment by BenConstable** [comment]
Hi,

That looks to be an error with your `BusServiceProvider` class, rather than with Phpspec or this extension. Try removing that class from your registered service providers, or fixing it, and running Phpspec again. Hopefully that should sort the issue.

**Comment by prodeveloper** [comment]
Thank you very much for your quick response.

Here is my bus service provider. It is really just stock one I haven't changed anything.

```php
<?php namespace App\Providers;

use Illuminate\Bus\Dispatcher;
use Illuminate\Support\ServiceProvider;

class BusServiceProvider extends ServiceProvider {

	/**
	 * Bootstrap any application services.
	 *
	 * @param  \Illuminate\Bus\Dispatcher  $dispatcher
	 * @return void
	 */
	public function boot(Dispatcher $dispatcher)
	{
		$dispatcher->mapUsing(function($command)
		{
			return Dispatcher::simpleMapping(
				$command, 'App\Commands', 'App\Handlers\Commands'
			);
		});
	}

	/**
	 * Register any application services.
	 *
	 * @return void
	 */
	public function register()
	{
		//
	}

}
```

**Comment by mikeerickson** [comment]
I am having the same issue (don't see if it was solved) but for me, it ONLY occurs when doing `phpspec run` from Homestead.

Running locally (on dev machine) all works as expected.

**Comment by BenConstable** [comment]
I've investigated this a bit more, and I can't see why you're both receiving this error. `Illuminate\Support\ServiceProvider` doesn't provide a `boot()` method, so you shouldn't be seeing an error when changing its signature.

Could you both confirm your Laravel versions with `php artisan --version`? I'm running `5.0.6` when testing the issue. You may be installing a package which is requiring an out of date or bleeding edge version of Laravel. Can you ensure that you're running the latest stable version?

@mikeerickson - that fact that you're seeing this only in your Homestead env suggests that your host machine's PHP env is `< 5.4`, or that your `error_reporting` settings in `php.ini` explicitly ignore `E_STRICT`.

**Comment by prodeveloper** [comment]
@BenConstable I think my issue maybe bleeding version. ```5.0.23```

**Comment by mikeerickson** [comment]
@BenConstable Here is my PHP info (not sure how to determine error level)   I am going to see what more information I can decipher

Homestead:: php --version
PHP 5.6.3-1+deb.sury.org~trusty+1 (cli) (built: Nov 19 2014 19:38:33)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans

**Comment by mikeerickson** [comment]
@BenConstable Checked php.ini settings and it is as follows on Homestead and locally:

error_reporting = E_ALL

**Comment by mikeerickson** [comment]
@BenConstable I am running Laravel 5.0.26

**Comment by mikeerickson** [comment]
@BenConstable I will create a new project from scratch (which will use latest Laravel and PHPSpec-Laravel) and get back to you with more details.

**Comment by mikeerickson** [comment]
@BenConstable OK, here is a quick and dirty sample which exhibits the issue (see readme)

https://github.com/mikeerickson/l5-phpspec

**Comment by mikeerickson** [comment]
@BenConstable ping ;-)

**Comment by mikeerickson** [comment]
@BenConstable BTW, I have found that running phpspec through gulp-phpspec it works fine, just gives the error when I use on command line with Homestead.

**Comment by BenConstable** [comment]
Haven't had any more reports of this issue, so going to close this for now.

**Comment by mikeerickson** [comment]
Sorry for leaving this open.  I have moved away from Laravel to Symfony.  However, you can be assured that when I do use Laravel, this will be a mandatory install as I use PHPSpec a lot still

**Comment by BenConstable** [comment]
No problem at all, just been having a clear out! 😊
