### ISSUE TITLE
How to mock laravel 5 aliases?

### ISSUE THREAD

**Issue by herusdianto** [BenConstable/phpspec-laravel#35]
Excuse me sir, can you post how to write a test for method that use laravel alias? So for example, i have this class:

```php
<?php namespace StatMe\Services;

use Cache;

/**
 * Class CachingService
 *
 * @package StatMe\Services
 */
class CachingService {

    /**
     * store user skin cache
     *
     * @param int    $user_id
     * @param string $skin
     */
    public function storeUserSkinCache($user_id, $skin)
    {
        Cache::forever('user.' . $user_id . '.skin', $skin);
    }

}
```

And i have this spec file:
```php
<?php

namespace spec\StatMe\Services;

use PhpSpec\Laravel\LaravelObjectBehavior;
use Prophecy\Argument;

class CachingServiceSpec extends LaravelObjectBehavior {

    function it_is_initializable()
    {
        $this->shouldHaveType('StatMe\Services\CachingService');
    }

    function it_stores_user_skin_cache()
    {
        $user_id = 1;
        $skin    = 'black';

        $this->storeUserSkinCache($user_id, $skin);
    }

}
```

How to mock that Cache::forever() method? Thank you.

**Comment by BenConstable** [comment]
Hi,

phpspec isn't set up to allow the mocking of static methods, and it's not something that this extension aims to provide. You can instead inject the caching service as a dependency, rather than using the facade, and mock it just as you would anything else.

**Comment by hackel** [comment]
@herusdianto FYI--you should still be able to use `Cache::shouldReceive('forever')->with('user.' . $user_id . '.skin', $skin)->andReturn()`...etc. within your phpspec tests.  I used this a lot, but now am rewriting everything to use dependency injection because these tests are incredibly slow.

**Comment by herusdianto** [comment]
@BenConstable @hackel Thank you sir, solved.
