### ISSUE TITLE
Using the package in Lumen

### ISSUE THREAD

**Issue by masterjus** [BenConstable/phpspec-laravel#37]
I've try to require your package to my lumen project but was confused when it downloaded all laravel framework. How can I resolve this?

**Comment by BenConstable** [comment]
Hi,

Thanks for the question. This package doesn't support Lumen, so you'll
probably just be better off using Phpspec without it. You shouldn't have
any trouble doing that really!

I'm away at the moment so can't point you to any good Lumen/Phpspec
tutorials, but I'm sure a quick a Google will turn some up.

Ben
