### ISSUE TITLE
This broke when upgrading to Laravel 5.4

### ISSUE THREAD

**Issue by simonhunt** [BenConstable/phpspec-laravel#41]
When running PHPSpec after upgrading to Laravel 5.4 returns the following:

```                                                                        
[ReflectionException]                                                   
Class Illuminate\Foundation\Bootstrap\DetectEnvironment does not exist 
```

Stack Trace:

```
Exception trace:
 () at /home/simon/Code/thephysics.guide/vendor/laravel/framework/src/Illuminate/Container/Container.php:681
 ReflectionClass->__construct() at /home/simon/Code/thephysics.guide/vendor/laravel/framework/src/Illuminate/Container/Container.php:681
 Illuminate\Container\Container->build() at /home/simon/Code/thephysics.guide/vendor/laravel/framework/src/Illuminate/Container/Container.php:565
 Illuminate\Container\Container->make() at /home/simon/Code/thephysics.guide/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:702
 Illuminate\Foundation\Application->make() at /home/simon/Code/thephysics.guide/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:208
 Illuminate\Foundation\Application->bootstrapWith() at /home/simon/Code/thephysics.guide/vendor/benconstable/phpspec-laravel/src/PhpSpec/Laravel/Util/Laravel.php:89
 PhpSpec\Laravel\Util\Laravel->createApplication() at /home/simon/Code/thephysics.guide/vendor/benconstable/phpspec-laravel/src/PhpSpec/Laravel/Util/Laravel.php:54
 PhpSpec\Laravel\Util\Laravel->refreshApplication() at /home/simon/Code/thephysics.guide/vendor/benconstable/phpspec-laravel/src/PhpSpec/Laravel/Listener/LaravelListener.php:52
 PhpSpec\Laravel\Listener\LaravelListener->beforeSpecification() at n/a:n/a
 call_user_func() at /home/simon/Code/thephysics.guide/vendor/symfony/event-dispatcher/EventDispatcher.php:174
 Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() at /home/simon/Code/thephysics.guide/vendor/symfony/event-dispatcher/EventDispatcher.php:43
 Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at /home/simon/Code/thephysics.guide/vendor/phpspec/phpspec/src/PhpSpec/Runner/SpecificationRunner.php:50
 PhpSpec\Runner\SpecificationRunner->run() at /home/simon/Code/thephysics.guide/vendor/phpspec/phpspec/src/PhpSpec/Runner/SuiteRunner.php:56
 PhpSpec\Runner\SuiteRunner->run() at /home/simon/Code/thephysics.guide/vendor/phpspec/phpspec/src/PhpSpec/Console/Command/RunCommand.php:178
 PhpSpec\Console\Command\RunCommand->execute() at /home/simon/Code/thephysics.guide/vendor/symfony/console/Command/Command.php:262
 Symfony\Component\Console\Command\Command->run() at /home/simon/Code/thephysics.guide/vendor/symfony/console/Application.php:848
 Symfony\Component\Console\Application->doRunCommand() at /home/simon/Code/thephysics.guide/vendor/symfony/console/Application.php:189
 Symfony\Component\Console\Application->doRun() at /home/simon/Code/thephysics.guide/vendor/phpspec/phpspec/src/PhpSpec/Console/Application.php:102
 PhpSpec\Console\Application->doRun() at /home/simon/Code/thephysics.guide/vendor/symfony/console/Application.php:120
 Symfony\Component\Console\Application->run() at /home/simon/Code/thephysics.guide/vendor/phpspec/phpspec/bin/phpspec:26
 {closure}() at /home/simon/Code/thephysics.guide/vendor/phpspec/phpspec/bin/phpspec:28
```

**Comment by BenConstable** [comment]
Thanks for bringing this to my attention - will take a look at this and the accompanying PR as soon as I can.

**Comment by simonhunt** [comment]
That's great Ben.

The first commit in the PR addresses the above exception (by replacing DetectEnvironment entry to LoadEnvironmentVariables as per the Laravel 5.4 extension guide - a simple fix.)

The second commit deals with another error which appears once the first exception has been removed. This has something to do with the logging entry in the Util/Laravel file:

```
[ReflectionException]                                                  
  Class Illuminate\Foundation\Bootstrap\ConfigureLogging does not exist
```

At present, I've dealt with it simply by removing the offending line on the basis that it makes it work (but presumably will introduce bugs for anyone planning to use the logging functionality - I'm personally not at the moment). I'm aware that this will need looking into further but not sure where to start.

**Comment by simonhunt** [comment]
I've been looking into this further and it seems that Laravel 5.4 now offers a CreatesApplication Trait.

I've tried out using this as a direct substitute for the existing createsApplication function and it seems to work fine. The only issue is that this removes the ability to set the APP_ENV. However, this can be overcome by adding the line responsible for this to the constructor function within this file.

I'll prepare a second PR for you to look over.

**Comment by mikeerickson** [comment]
I am guessing that Laravel does NOT follow semver.  Seeing as this was a minor (5.3 -> 5.4) version update, it should not be introducing breaking changes in the API?

**Comment by BenConstable** [comment]
@mikeerickson the API I'm using for this part of the package isn't documented *as such*, but you're correct, Laravel doesn't really follow semver. I believe there was some discussion on that a while back and they landed on a non-semver versioning system.

@simonhunt that's great, I found that trait too. Rather than using the trait directly though it'd be better to simply resolve the `Illuminate\Contracts\Console\Kernel` instance out of the container and call its `bootstrap()` method. That would allow us to keep the [custom bootstrap path functionality](https://github.com/BenConstable/phpspec-laravel#app-bootstrap-path). You're right, this would likely lead to a new release, although I'll go back over the previous `5.x` Laravel releases first to check if that `Kernel` API was in place already (as I may have just missed it).

Feel to free to update your existing PR or to create a new one, or alternatively I should have some time to look at this in the next few days.

**Comment by mikeerickson** [comment]
@benconstable ya, it seems like it.  This has been happening for quite some time (breaking changes in minor version updates)

Is this the only outstanding item keeping it from working with laravel 5.4

**Comment by simonhunt** [comment]
@benconstable Spot on... I've rewritten the createApplication method using the code from the tests/TestCase in Laravel 5.3 (which is identical to the code in the createsApplication Trait in 5.4) and it works in both 5.3 and 5.4. I've removed my previous PR and added a new one containing these changes.

My only remaining question is the purpose of the line: 

```
Carbon::setTestNow(Carbon::now());
```

Looks as though it can now be removed?

**Comment by BenConstable** [comment]
@simonhunt thanks, looks good 👍  I'll merge it and you're right, so that `setTestNow()` call is redundant so I'll get it remove.

@mikeerickson that's correct.

**Comment by mikeerickson** [comment]
@BenConstable Is it ready for 5.4 now?

**Comment by BenConstable** [comment]
I'll release a new version shortly that contains the fix.

**Comment by simonhunt** [comment]
Just to confirm, I've tested the fix in both 5.3 and 5.4 (so the fix shouldn't need a new version after all).

**Comment by BenConstable** [comment]
Yep that's fine, it's compatible back to 5.0. The new version will just be a simple patch relaase.

**Comment by mikeerickson** [comment]
@BenConstable Thanks for your efforts, I am going to be trying this out later this evening!
