### ISSUE TITLE
Quick and Dirty Example

### ISSUE THREAD

**Issue by mikeerickson** [BenConstable/phpspec-laravel#44]
Any of you `phpspec` and `phpspec-laravel` users have (or would be willing to create) a bare bones laravel application with `phpspec` installed and configured to work?  Just a simple "hello world' repo would go a long way

I have been fighting with this all day and cant seem to get it working correctly.  I have used it in the past (and had it working) but that was Laravel 5.1ish   

Thanks in advance, I would be most grateful

**Comment by mikeerickson** [comment]
Just for some background, I did the following

```
$ composer require benconstable/phpspec-laravel --dev
```

I was under the impression that the latest master version of `phpspec-laravel` is the current version and works with `Laravel 5.4`?

When I run `phpspec run` and extension is active, it throws an error

```
[PhpSpec\Exception\Configuration\InvalidConfigurationException]
  Extension class `0` does not exist.
```

**Comment by BenConstable** [comment]
Hi @mikeerickson,

Could you supply the exact version of Laravel and Phpspec you're using? Also, you can just `composer require-dev benconstable/phpspec-laravel` as the latest stable version supports 5.4.

**Comment by mikeerickson** [comment]
@BenConstable Hey there... Sorry I didnt reply, but I have it all working now.   Sorry about that
