### ISSUE TITLE
Hey, Can you transfer repository, if u not have oportunitites to support it?

### ISSUE THREAD

**Issue by Insolita** [BenConstable/phpspec-laravel#51]
?

**Comment by Insolita** [comment]
https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-a-repository-to-another-user-account-or-to-an-organization

**Comment by BenConstable** [comment]
Thanks for the suggestion - please see my latest update here https://github.com/BenConstable/phpspec-laravel/pull/47.
