### ISSUE TITLE
Merge open PRs, and get this repo updated

### ISSUE THREAD

**Issue by BenConstable** [BenConstable/phpspec-laravel#52]
I've neglected this repo, and there are some open PRs that need merging (in particular, Phpspec 4 support).

I'm going to get the open PRs merged and get this repo updated. Regarding new features, I'll probably not add anything to the package going forwards unless it's really going to be useful. I'm not working with Phpspec anymore, so am personally out of touch with it.

I'm going to use some time next weekend (29/04/2018) to get the PRs merged, and give this repository a tidy up, so please expect updates then.

In the meantime, please use the fork @ShawnMcCool has kindly if you urgently need Phpspec 4 support [created](https://github.com/heybigname/phpspec-laravel).

Thanks for your patience!

**Comment by BenConstable** [comment]
Tracking this via the [v4 milestone](https://github.com/BenConstable/phpspec-laravel/milestone/1).

**Comment by BenConstable** [comment]
v4 is now released.

**Comment by mikeerickson** [comment]
Thank you for your efforts Ben!
